### ISSUE TITLE
Remove external libraries from the code

### ISSUE THREAD

**Issue by frisso** [netgroup-polito/fg-gui#12]
Do not include the code of the external libraries (i.e., vnf template and nffg library); include them in your project as submodules in order to avoid code duplication.

**Comment by frisso** [comment]
@farmanullahcs : the link to vnf_template_library submodule looks pretty old. Can you update it with a newer version and make sure that everything still works?

**Comment by farmanullahcs** [comment]
Updated vnf-template-library with [bcbb757](https://github.com/netgroup-polito/frog4-gui/commit/bcbb757890fe2a4f664b5597d016536af7cd979b)

**Comment by frisso** [comment]
Thanks,
