### ISSUE TITLE
Integrate the GUI with the UN

### ISSUE THREAD

**Issue by frisso** [netgroup-polito/fg-gui#19]
Modify the backend in order to interface with the UN.
Step 1: use directly the sqlite DB in the UN
Step 2: modify the backend adapter of the dashboard in order to read/write data through the REST interface of the UN.

**Comment by frisso** [comment]
@farmanullahcs This has been done time ago. Can you confirm? If so, we can close this issue.

**Comment by farmanullahcs** [comment]
GUI integrated with the frog4-orchestrator and then to the Un-orchestrator.

**Comment by ivanocerrato** [comment]
I'm a bit confused about this. 
Because the northbound API of the UN-orchestrator has not been yet changed (e.g., it expects that the NFFG id is provided from the extern).

**Comment by frisso** [comment]
So, should we reopen the issue?

**Comment by ivanocerrato** [comment]
@farmanullahcs am I right? If yes, I would reopen the issue.

**Comment by farmanullahcs** [comment]
@ivanocerrato : Yes, you're right

**Comment by ivanocerrato** [comment]
If I understand correctly, this is not a problem of the GUI, but of the UN.
I would let this issue closed.
I opened this issue https://github.com/netgroup-polito/un-orchestrator/issues/124 on the universal node

**Comment by farmanullahcs** [comment]
I agree.
