### ISSUE TITLE
Delete button

### ISSUE THREAD

**Issue by ivanocerrato** [netgroup-polito/fg-gui#27]
Add a `delete`  button that deletes the graph currently shown.

**Comment by giacomoRanieri** [comment]
This Button should delete the whole content of the graph, or just the selected element?

**Comment by ivanocerrato** [comment]
It would be better to introduce the possibility to delete the selected elements..
But note that, if you delete, e.g., a VNF,  the command sent to the UN should also delete the flows involving such a VNF. The same applies to the endpoints

**Comment by frisso** [comment]
button should delete the entire graph, maybe after asking for confirmation; I work suggest some icon such http://www.softicons.com/application-icons/qetto-icons-2-by-ampeross/trash-icon

**Comment by giacomoRanieri** [comment]
There is no need to delete the entire graph, unless you need to delete it from the universal node. If you want to clean a graph you simply create a new one.

**Comment by ivanocerrato** [comment]
Why there is no need? I may want to delete a graph deployed on the UN.
In fact the UN allows to delete the entire graph https://github.com/netgroup-polito/un-orchestrator/blob/master/orchestrator/README_RESTAPI.md

**Comment by giacomoRanieri** [comment]
This is a different matter. You have to first distinguish between a graph loaded from the universal node form a graph loaded from a different source.
With these information, I've understood the problem.
I'll think to a solution that could work on both repository and universal node based on the source of the graph

**Comment by frisso** [comment]
Agreed.
Deleting a graph from the UN, without replacing it with another graph, is definitely important.

**Comment by giacomoRanieri** [comment]
Functionality now available on master.
