### ISSUE TITLE
info about project authors is not accurated enough

### ISSUE THREAD

**Issue by mauriciovasquezbernal** [netgroup-polito/fg-gui#29]
Project info (available for example at http://130.192.225.236:9999/info/) only shows the authors of the GUI interface. I think it should be modified to show also the authors of the back-end or a least clarify it.

**Comment by ivanocerrato** [comment]
This file https://github.com/netgroup-polito/fg-gui/blob/master/nfg/static/pages/modals/guiInfo.html contains several people who worked (or are still working) in the frog projerct.
