### ISSUE TITLE
Bug in the NF's configuration screen

### ISSUE THREAD

**Issue by piscoroma** [netgroup-polito/fg-gui#33]
In the NF's configuration showed, the ipv4-configuration container is not shown.

**Comment by giacomoRanieri** [comment]
Should be resolved with pull request #34.

**Comment by frisso** [comment]
@giacomoRanieri : can we safely delete branch general-improvement?
(i'm crazy with all these branches)

**Comment by frisso** [comment]
@piscoroma : can we safely remove branch FixNFsConfiguration?
Thanks.

**Comment by piscoroma** [comment]
Done.

Il 03/Lug/2017 16:42, "Fulvio Risso" <notifications@github.com> ha scritto:

**Comment by frisso** [comment]
Thanks!

**Comment by giacomoRanieri** [comment]
@frisso general-improvement has some minor change still in progress ( like interface dragging algorithm, which now is very annoing ) so, if is not a big problem, I'd like to keep that branch

**Comment by frisso** [comment]
Got it. Thanks.
