### ISSUE TITLE
API towards orchestrators

### ISSUE THREAD

**Issue by ivanocerrato** [netgroup-polito/fg-gui#37]
The API towards orchestrator has to distinguish, using PUT and POST, the creation and the update of a graph.
In case of creation, it does not specify the graph ID, which is received by the orchestrator as a result of the creation.

**Comment by farmanullahcs** [comment]
Fixed in the branch [frog4-deployment](https://github.com/netgroup-polito/frog4-gui/tree/frog4-deployment)
