### ISSUE TITLE
Config.ini cleanup

### ISSUE THREAD

**Issue by frisso** [netgroup-polito/fg-gui#38]
We should replace all the address/port/protocol in the config.ini with something simpler, such as:

   xx_endpoint= http://serveraddress:port/starting_url

**Comment by farmanullahcs** [comment]
Is it correct  ?

[fg-gui]

>  gui_endpoint = http://localhost:9999/

[orchestrator]

>  orchestrator_endpoint = http://localhost:8080/NF-FG/

[graph-repository]

>  graph_repository_endpoint = http://localhost:8081/v2/nffg/

[vnf-template]

>  vnf_template_endpoint = http://localhost:8081/v2/nf_template/

**Comment by frisso** [comment]
Looks perfect to me.
@rbrtbnfgl , @gabrielecastellano , @ivanocerrato : are you ok?

**Comment by ivanocerrato** [comment]
To me it's ok.

**Comment by farmanullahcs** [comment]
Fixed in the branch [frog4-deployment](https://github.com/netgroup-polito/frog4-gui/tree/frog4-deployment)

**Comment by frisso** [comment]
Thanks, Farman.
