### ISSUE TITLE
Edit graph ID

### ISSUE THREAD

**Issue by frisso** [netgroup-polito/fg-gui#7]
Each forwarding graph includes a graph ID, a name and a description.

1) Show the "name (id: xxx)" on the right side of the screen (currently it shows only "id"), unless the name is void; in this case show only ID.

2) When clicking on that link, open a window that allow to customize both ID, name, and description with three strings.

**Comment by cuttica** [comment]
Do we use the name of the JSON file or we assume that will be a field named "name" instead?

**Comment by frisso** [comment]
In the nffg 'root' there are three attributes: ID, name, and description. I would suggest to use those ones.
